### ISSUE TITLE
Is it compatible with Express 4.X?

### ISSUE THREAD

**Issue by alvarotrigo** [jaredhanson/connect-flash#17]
Is it compatible with Express 4.X?

**Comment by stuartpb** [comment]
https://github.com/expressjs/flash is the Express 4 version.

**Comment by isimmons** [comment]
@alvarotrigo Yeah I thought everything was good because I reverted back to connect-flash and everything works fine (expressjs/flash not working). Then I read this and realized I was not using the message type.

Here is something I just did which works.

set messages variable as object containing separate error/info messages
```
res.render('signup', {
      title: 'Sign-up Form',
      messages: {
        error: req.flash('error'),
        info: req.flash('info')
      }
```
Problem here is you end up with an empty array if there are no info messages or visa versa so in your template you have to check for array.length
 
flash them where ever like normal
```
if (err) {
              var message = getErrorMessage(err);
              req.flash('error', message);
              req.flash('info', 'foobar');
              return req.res.redirect('/signup');
            }
```

In my ejs template
```
<% if (typeof messages.error !== 'undefined' && messages.error.length > 0) { %>
    <p class="error"><%= messages.error %></p>
<% } %>
<% if (typeof messages.info !== 'undefined' && messages.info.length > 0) { %>
    <p class="info"><%= messages.info %></p>
<% } %>
```
Could place this in it's own template to be included or create some type of helper function globally available to all views like
```
<% if(messages) renderMessages(messages); %>
```

Just a thought.
